### ISSUE TITLE
Use Labels for Heredoc-like Sections

### ISSUE THREAD

**Issue by puria** [dyne/tgcom#12]
As a developer, I want to use labels to specify start and end keywords for commenting sections so that I can handle heredoc-like structures.

**Example:**
`tgcom --file main.go --start-label START --end-label END --action comment`

**Comment by FilippoTrotter** [comment]
@puria until now, I've added the option for labels only in the case of a single file. Should it also be added in the case of multiple files? If yes, how should the command be?
